### ISSUE TITLE
Tracking Issue

### ISSUE THREAD

**Issue by hmharvey** [UW-CSE442-WI20/FP-hushhhhhhhz#2]
## Deliverables
- [ ] Introduction text 
  - [x] text
  - [x] teasers
  - [x] gif background
- [ ] History 
  - [x] timeline (keep most important info so we fit it in the space)
  - [x] reformatting
  - [ ] animation vs scroll trigger (is animation, once it is done one time keep it static)
- [ ] Stream Cipher (Vigenere)
  - [x] reformat explanation
  - [x] encryption
  - [x] decryption interaction 
  - [x] space for users to test their own phrases (encryption)
- [ ] Block Cipher (Playfair) 
  - [x] introduce rules (column, row, box, uneven lengths/double letters)
  - [x] reformat explanation
  - [ ] try to figure out timing thingy
  - [x] encryption
  - [x] decryption interaction
  - [x] reformat encryption interaction!!
  - [x] space for users to test their own phrases
- [x] Symmetric Keys 
  - [x] encryption
  - [x] decryption
  - [ ] integrate updated animations
- [x] Asymmetric Keys + RSA
  - [x] encryption
  - [x] decryption
  - [x] integrate updated animations
- [x] transition window
  - [x] figure out text/images to include (back to the future???)
- [ ] Hash and RSA formatting
- [x] table of contents clickability
- [x] choose color scheme
- [x] MAKE SCROLLING BETTER (when you scroll, it should go to the full next page :-))

#### Our Docs
- [Text Planning](https://docs.google.com/document/d/1MERyX7hqxTranC4dgEdC87Hogw8eMh2TmozcwNbTiwQ/edit?fbclid=IwAR2Q28KpXstjdbRAewoU6SNXOdx7BfcPU6SliH9jA6XcH2bYyZMcHZNme98&pli=1)
- [Figma Design](https://www.figma.com/file/SYs3Vhh0uq5zhwOYRfU1be/Final-Project-Planning?node-id=0%3A1)

#### Tutorials and ideas
- [Scrolling Tutorial](https://vallandingham.me/scroller.html?fbclid=IwAR1BZGW8cIFledBDDfXF2FnRrrA0ZEBz2dz7yAar8N0TY6PwPmCbBxPIrSA)
- [Gun visualization](http://letsfreecongress.org/)
- [Homeless visualization](https://www.theguardian.com/us-news/ng-interactive/2017/dec/20/bussed-out-america-moves-homeless-people-country-study?fbclid=IwAR1WkAIuDs21CaxJ5fWFkq-E0dws_XORPNGstSmywmWsojE6jUmH2N1ggT8)
- [The glowy colors!!](https://blog.envylabs.com/loops-d3-timer-2c5f4313588)
- [Fixed while scrolling](https://stackoverflow.com/questions/49043379/how-to-keep-x-axis-in-fixed-position-while-scrolling-using-d3-js?fbclid=IwAR31caBH9xxMkeFHlBRSpv565yEtN-4Px43jPObCkcWou1Xby4650_fp7TQ)
- [crypto info](http://www.quotium.com/resources/importance-cryptography/)

#### GIF
https://images.app.goo.gl/6o2Borw6Lw9MPEmG6

**Comment by LiorLev** [comment]
•	Overall stuff:
o	Make bubble animation stick after it is done one time
 
 
•	Delay on text bubbles - make faster (both flowers)
•	Fix table of contents
•	Divs on intro - add radius to divs
 
 
•	Center history
•	Make title bigger
•	Maybe a bit more padding on the boxes
 
•	Less text in history bubble
•	Change titles
•	Move start over to the encryption bubble
•	Adding space between math and encryption
•	Making math bigger
•	Fade in text after bubble shows up (also for button)
 
•	Change layout (maybe vertical)
•	Fix the last line of the grid for encryption (doesn’t hover rn)
•	Make keys clickable
 
•	Fix bubble size
•	Fade in text after bubble shows up (also for button)
•	Fix layout of the animation bc ugly rn
•	Change some colors :)
•	Change font to roboto for encryption
 
 
•	Color diff for encrypt and decrypt
•	Change grid format
•	Other formatting and spacing :p
 
•	Make text bigger
•	Center it
 
•	Fix spacing
•	Fix sizes of keys
•	Make keys grow
•	Color of keys make it something else 
o	Highlight text in the story with that color
•	Delays/duration make it slower :)
•	Add title + start animation button
o	Separate the animation from the title (maybe add border around it)
 
 
•	Title for asymmetric should be something like (to prevent that, asymmetric was created….) + start animation button
•	Remove public and private for everyone
•	Change color of matt's keys
•	Add colorings to the text of the story to follow the keys / icons whichever one is easier/ helps understand best
•	Delay/duration slower
•	Change sizing of everything and spacing
•	Add story line to be on the top
